import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/providers/ToastProvider";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";
import { Providers } from "@/providers/StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
        <ToastProvider/>
      
        <NextAuthSessionProvider>
        {children}
        </NextAuthSessionProvider>
        </Providers>
        
        </body>
    </html>
  );
}
